### ISSUE TITLE
Link issue & author on CHANGELOG

### ISSUE THREAD

**Issue by roby2014** [GameDevTecnico/cubos#1167]
# Problem
Current CHANGELOG does not link the issue nor the author.

# Solution
Would be cool to have links, e.g:

- Implemented ABC ([#123](google.com), [roby](google.com))

**Comment by RiscadoA** [comment]
Although this would be nice to have, we decided not do to do this earlier because it is really cumbersome to setup, and also makes the 'raw' markdown really hard to read.

**Comment by RiscadoA** [comment]
Closing this I guess? If you think we should follow with this feel free to reopen.
