### ISSUE TITLE
Reduce performance overhead of directional shadow support

### ISSUE THREAD

**Issue by tomas7770** [GameDevTecnico/cubos#1345]
# Description

The newly added support for [directional lights casting shadows](https://github.com/GameDevTecnico/cubos/pull/1338) has resulted in a drastic performance loss (about half in some cases), even when shadows aren't enabled, due to changes in the deferred shading.

# Expected behaviour

When shadows are disabled, the performance impact of merely supporting them should be minimal.

**Comment by RiscadoA** [comment]
Damn we really need to improve this on 0.5 :skull: samples become outright unplayable on my laptop

**Comment by tomas7770** [comment]
Lowering the max number of cascades and/or removing the directional light greatly improves performance. Adding more directional lights worsens it. Maybe the bottleneck is passing the cascade matrices to the GPU?
