### ISSUE TITLE
Add a method of saving settings back to a file

### ISSUE THREAD

**Issue by SrGesus** [GameDevTecnico/cubos#1349]
# Problem
Currently you can read settings from file but not write back to it.

# Solution
Add a method to the settings class (I kind of don't like this because everything I/O related to settings is in the plugin instead of the class)

# Alternatives
Perhaps a system that runs periodically? Not a big fan

Store back to file on every change? Would be doable when #456 is implemented

**Comment by RiscadoA** [comment]
Thanks for creating the issue! One other alternative would be to have some sort of SaveSettingsEvent which the settings plugin detects. This way you could keep the Settings class clean

**Comment by SrGesus** [comment]
Yes, sounds like #456 right? 
Will be looking into it

**Comment by RiscadoA** [comment]
> Yes, sounds like #456 right? Will be looking into it

Yeah you can couple it with that one, but I don't know if it's a good idea to always save the settings when they are changed :thinking: I guess that should be configurable with its own setting :eyes:

**Comment by SrGesus** [comment]
Since mValues is private it is just be easier to do the serializing as a Settings class method but a question remains:

If there is a field, e.g - `"assets.path" = "/assets/"`

What should the settings.json look like?

1. 
```json

{
  "assets.path": "/assets/"
}
```
2. 
```json
{
  "assets": {
    "path": "/assets/"
  }
}
```

I'm leaning 1 because it's:
- Much more trivial to implement
- More efficient in both serialization and deserialization

**Comment by RiscadoA** [comment]
> Since mValues is private it is just be easier to do the serializing as a Settings class method but a question remains:
> 
> If there is a field, e.g - `"assets.path" = "/assets/"`
> 
> What should the settings.json look like?
> 
> 
> ```json
> {
>   "assets.path": "/assets/"
> }
> ```
> 
> 
> ```json
> {
>   "assets": {
>     "path": "/assets/"
>   }
> }
> ```
> 
> I'm leaning 1 because it's:
> 
>     * Much more trivial to implement
> 
>     * More efficient in both serialization and deserialization

Yeah I would say go for the first one. The problem is that then whenever the user opts for the second way the engine replaces it by the first one.
Maybe we should remove the logic for handling 'scopes' entirely, and just have everything inline as you suggested. What do you think?

**Comment by SrGesus** [comment]
> Maybe we should remove the logic for handling 'scopes' entirely, and just have everything inline as you suggested. What do you think?

I think we should keep it since it's valid JSON and the performance impact on deserialisation is minimal since it should not run more than a couple times (if not just once on startup) and it might be easier for a user to write.
