### ISSUE TITLE
Convert Car demo to ECS

### ISSUE THREAD

**Issue by joaopat98** [GameDevTecnico/cubos#149]

**Comment by Ev1lbl0w** [comment]
I've created the [`demo-ecs`](https://github.com/GameDevTecnico/cubos/tree/demo-ecs) branch for working on this then

**Comment by Ev1lbl0w** [comment]
Initial implementation done with https://github.com/GameDevTecnico/cubos/commit/77d95d8d3615a13b644769e58d6ea49a8d9d233a
