### ISSUE TITLE
Archives

### ISSUE THREAD

**Issue by joaopat98** [GameDevTecnico/cubos#16]

**Comment by RicardoEPRodrigues** [comment]
Perhaps you want to implement something already present in C++17, `std::filesystem`.

https://en.cppreference.com/w/cpp/filesystem

**Comment by RiscadoA** [comment]
Not really, the purpose of archives are to provide a virtual file system which can handle compressed archives as well as default directories. What filesystem does is simply act as a wrapper to the OS file functions. `std::filesystem` does have it place in the `StandardArchive` implementation.

**Comment by joaopat98** [comment]
- [ ] Basic Archive Implementation
- [ ] Implement loader just for .qb files using Archive
