### ISSUE TITLE
Add Window plugin

### ISSUE THREAD

**Issue by rsubtil** [GameDevTecnico/cubos#197]
With the Cubos class #192 being implemented, making the window system and renderer plugins is a natural fit.

The objective is to completely handle all the window/renderer logic internally that the user had to manually do up to this point.

**Comment by rsubtil** [comment]
(from meeting)

Startup system should handle window creating and displaying. Two systems exists for event polling and switching back buffer. Later on the renderer needs to run before back buffer stage.

**Comment by RiscadoA** [comment]
I split this issue into two, one for the Window and another for the Renderer
