### ISSUE TITLE
Collisions plugin

### ISSUE THREAD

**Issue by RiscadoA** [GameDevTecnico/cubos#199]
# Design

All of the collision related code is added through the `collisionPlugin`.
This plugin adds:
- the `EventPipe<Collision>` resource.
- the `Collider` component, which stores a group of collision objects.
- the `generateCollisions` system, which queries all entities with colliders and writes `Collision` events.

The `Collision` event should contain all data necessary to solve collisions later on (will be useful for the physics plugin).

The initial version will not be optimized as to perform spatial division techniques, and should aim to Just Work:tm: 

# Requirements

- Colliders identify a single collision shape and are associated to a single entity.
- Colliders store the root, or upmost entity of its collider sub-tree.
- Colliders may be flagged as roots.
- Colliders never collide with others with the same root.
- Static colliders should not check for collisions with other static colliders, should be easily toggleable (can be used by the physics engine to optimize objects at rest).
- We should have tags/masks for colliders.
- Triggers.
- It should be possible to send rays.
- Decide which collider shapes should be supported, initially (box, sphere, capsule, cylinder, plane).  
- Spatial indexing data structure - initially 2D, should be modular to allow devs to implement 3D easily.

# To do

- See how triggers could be implemented.
- Understand the update loop.
- Find out how to handle multiple collisions at once.

# Notes

- Greedy meshing to generate collision faces for voxel grids (always rectangular).
- Transform the smallest collider faces into the local space of the larger collider, instead of transforming both of them to world space.
- Apply Separating Axis Theorem - the biggest object is already aligned.
-

**Comment by DiogoMendonc-a** [comment]
@RiscadoA

**Comment by RiscadoA** [comment]
Closed in favor of #522 and other issues.
