### ISSUE TITLE
Add an asset explorer to the editor

### ISSUE THREAD

**Issue by RiscadoA** [GameDevTecnico/cubos#212]
Should be easy to define new assets (through the .meta format) from the UI.

**Comment by RiscadoA** [comment]
We'll need to add functionality to the `AssetManager` to allow us to read its state: which assets were imported, are they loaded, which type are they, etc.

**Comment by RiscadoA** [comment]
I've been thinking about this while redesigning the asset manager.
The asset explorer should:
1. show all assets defined in .meta files (i.e., imported assets).
2. allow selecting and *opening?* assets
3. allow visualizing and editing import properties of existing assets - rename, etc
4. allow importing new assets - creating new .meta files, ideally should be automated


1 and 2 are the most critical. This would allow us to see existing scene assets and open them, for edition.

**Comment by rsubtil** [comment]
From the meeting, we decided the following behaviors to be implemented for the asset explorer:

- When opening assets, the explorer will send an "asset opened" event to the ECS world. This way, the specific tools to open assets will be listening for such events, and get delegated with the task of editing assets.
- To know whether an asset is "openable" in the editor or not, those tools register themselves in the asset explorer by specifying a compatible extension.
- Opening a scene will reset the ECS world, starting from scratch.
