### ISSUE TITLE
Move engine component declarations somewhere else

### ISSUE THREAD

**Issue by RiscadoA** [GameDevTecnico/cubos#252]
Right now the component declarations are in the `engine/include` directory, next to 'normal' include files.
This gets confusing because component declarations are not supposed to be included directly, so, it makes sense to move them into another directory.
Maybe `engine/components`? Not sure if we should split it further into plugins.

E.g.:
`engine/components/grid.hpp`
`engine/components/position.hpp`
...

or

`engine/components/renderer/grid.hpp`
`engine/components/transform/position.hpp`
...

**Comment by rsubtil** [comment]
I vote the second option, it helps in showing what areas a given component is acting on.

**Comment by RiscadoA** [comment]
After #238 is merged I will work on this (there are no components to move anywhere right now).
