### ISSUE TITLE
Add initial Scene editor

### ISSUE THREAD

**Issue by RiscadoA** [GameDevTecnico/cubos#265]
UI should be created to allow us to open a scene and see its sub-scenes and entities.
We should be able to edit them using the #264.
They should also be actually spawned into the ECS world so that they can rendered.

**Comment by roby2014** [comment]
https://github.com/mlabbe/nativefiledialog might be interesting for opening the scene file via file dialog.

**Comment by RiscadoA** [comment]
I don't think a native file dialog would be the more fitting tool to use in *Cubos* since we use our virtual file system.
Instead I think we should have our own 'file explorer' or something, inside the editor.

Still, a native file dialog would make sense for #262 when importing external assets into Cubos.
For now lets just keep this feature simple and allow loading existing `Scene` assets, and also allow creating new `Scene` assets.

**Comment by RiscadoA** [comment]
The scene editor may be open for either:
- a new scene, without a matching asset
- editing an existing scene asset

Ideally we would have two buttons: 'save' and 'save as'. The 'save' button would be greyed out in the first scenario.
When we press 'save as', we can choose:
- a path for the new scene file.
- the name of scene asset (maybe we should force this to be the path of the .meta file to avoid confusion?).

There's also the problem of other scenes which use this as their sub-scene becoming invalid due to an entity being deleted. Not sure how we would fix this.

**Comment by RiscadoA** [comment]
This issue will be closed when inspecting is merged - editing will be left to #358.
