### ISSUE TITLE
Implement tag inheritance in the dispatcher 

### ISSUE THREAD

**Issue by rsubtil** [GameDevTecnico/cubos#292]
The dispatcher will support tag inheritance to re-use configurations for similar behaviors:

```cpp
cubos.tag("fixed-step").addCondition(...);
// Tag "fixed-step" runs at a fixed 60 FPS
cubos.tag("physics").inheritsTag("fixed-step").addSystem(...);
// Tag "physics" inherits configs from "fixed-step"
```
Internally, tags are just temporary references to a `SystemSettings` struct, but whether we want inheritance to perform copies or reference existing objects will have an impact on the usage of this feature. With the following setup:
```cpp
cubos.tag("A").addCondition(a);
cubos.tag("B").inheritsTag("A");
cubos.system(b).tagged("B");
```
If the user now does:
```cpp
cubos.tag("A").addSystem(c);
```
Would system `b` implicitly have this new system `c` as well? If yes, this requires having inheritance be a reference to an existing setting. If it was a copy, `b` wouldn't have this new system `c` (although subsequent systems with tag `b` would now have it)

**Comment by RiscadoA** [comment]
I don't understand what you mean by adding a system to a tag. I think we should force the user to always do it in the opposite order: the systems are tagged, not added to tags.

So, when you use `.tag("A")` you would get something with the same interface as the `SystemBuilder` - you're just applying the same properties you could apply to single systems, but now to groups of systems.

But regarding you question, I think it shouldn't be a copy - that would make the order relevant, and we want to avoid this at all costs due to the way plugins work.

**Comment by rsubtil** [comment]
The issue is that, by working with references, users cannot tweak system settings to change slightly from the tag, because when a system gets tagged it essentially gets the `SystemSettings` with that requested tag, which might be shared to more systems:
```cpp
cubos.tag("A").addCondition(a);

// System b has condition a
cubos.system(b).tagged("A");

// System b and c have conditions a and d
cubos.system(d).tagged("A"). addCondition (d);
```

**Comment by RiscadoA** [comment]
I think that what should actually happen is, while 'building' the dispatcher, we store the properties of all tags and systems (their tags too), individually.
Then, when we 'compile' the dispatcher, we actually apply the tag's properties to the tagged systems recursively.

For example,
```cpp
cubos.system(x).tagged("B");
cubos.system(y).tagged("B").addCondition(c);
cubos.system(z).tagged("A");

cubos.tag("A").addCondition(a);
cubos.tag("B").tagged("A").addCondition(b);
```
would output three systems, where:
- `x` runs iff `a` and `b`.
- `y` runs iff `a` and `b` and `c`.
- `z` runs iff `a`.

**Comment by rsubtil** [comment]
Sounds good! I'll postpone settings coming tags until the compilation step then to support this use case.
