### ISSUE TITLE
Allow assets to be hot-reloaded

### ISSUE THREAD

**Issue by RiscadoA** [GameDevTecnico/cubos#301]
This would be useful for implementing editor features, but may require some redesign of the asset manager and asset handles system.
Further discussion is necessary.

**Comment by RiscadoA** [comment]
So, what features do we really need for the asset manager?
- Creating new assets at runtime, which may not even have a string name (e.g., procedurally generated content) - we could use a `UUID` to identify them.
- Creating 'named' assets (e.g., `"car/grid"`).
- Creating 'weak' handles to assets from their ids (handles which don't keep the asset alive).
- Upgrading 'weak' handles to 'strong' handles (handles which perform reference counting on the asset) - may fail, in which case the asset needs to be loaded.
- Reading asset data from a strong handle.
- Writing asset data from a strong handle.
- Allow other systems to detect writes on a given asset (this would give us hot-reloading).
- Integrating nicely with the ECS.

**Comment by RiscadoA** [comment]
## Handles

Assets are identified in two possible ways: by their ID (assigned dynamically when found) or by their name (some assets may be unnamed).
This logic is encapsulated through the `Asset` class, which acts as an handle to an asset.

### Reference counting

We shouldn't leave the responsibility of freeing unused asset memory to the developer. So, implementing some kind of
reference counting on the asset handles is a must.

An handle can either be *weak* or *strong*. *Weak* handles do not increase the reference count of the asset: they only identify the asset, they don't keep it alive. Strong handles do increase the reference count.

### Upgrades and downgrades

Weak handles can be upgraded to strong handles through the *Assets* object, and strong handles can be downgraded t weak handles whenever necessary. Strong handles cannot be created directly, but weak handles can, using the asset's name (even if it has not been loaded yet).

### Serialization and deserialization

When an asset handle is serialized, the respective ID or name is serialized.
When deserializing, a weak handle is created.

## Assets

The `Assets<T>` object is a resource responsible for storing and garbage collecting assets of the type `T`.
All access to the assets data is made through this object. It provides four methods:
- `load(Asset) -> Asset`: loads the given asset if its not already loaded, returns a strong handle pointing to it.
- `store(Asset, T&&)`: stores the given data associated to the given asset handle. If asset is already loaded, its data is overwritten.
- `read(Asset) -> const T&`: provides read access to the given asset. Aborts if the handle isn't strong.
- `write(Asset) -> T&`: provides write access to the given asset. Aborts if the handle isn't strong. Increments the version count of the asset.

## Plugin

All of this logic can be exposed through the assets plugin.

## Loaders

TODO

**Comment by RiscadoA** [comment]
Basically, all handles are weak by default. Imagine you want to refer to an asset when it isn't loaded - you use a weak handle. For example, both `load` and `store` can receive weak handles, which are returned as strong handles since the asset is guaranteed to be loaded after the method is called.

**Comment by RiscadoA** [comment]
Regarding the loaders solution here, I'm still thinking of a better way to do it, since we need a centralized place to manage the asset meta files.

**Comment by RiscadoA** [comment]
After further analysis and discussion of this redesign, I've come up with the following redesign plan.
This is closer to the current system which makes it easier to implement.

# Overview

## Assets

The current asset manager will be renamed to `Assets`, just to reduce the verbosity. This object will handle, and provide:
- storing assets.
- access assets.
- load assets.

It won't handle importing assets from source assets: that functionality will be left to another plugin.

## Bridge

Bridges are the objects responsible for loading (and optionally saving) an asset type. They should be named, and are assigned through an asset either through its extension or by manually specifying the bridge to be used in the `.meta` file.

Bridges have access to the `Assets` objects which allows them to load assets recursively.
This is useful for handling dependencies, like sub-scenes.

This is pretty much the `Loader` we have already implemented, but extended to allow saving assets too.
Other naming suggestions are welcome.

## Meta files

Imported asset files should have a corresponding `.meta` in the same directory as them. For example, `car.grd` and `car.grd.meta`.
The `.meta` files mark an asset as imported, and may either be empty or contain some extra information to specify import options.

Files without a corresponding `.meta` are just ignored by the `Assets` object.

## Handles

`Asset` handles are one of the big changes. We should start using something along the lines of what was discussed in the previous proposal: weak handles & strong handles, and access only through the `Assets` object.
This new design allows us to make assets reloadable easily, as discussed previously.

# Interface

## Assets

- `addBridge<B>(constructorArgs)`: adds a new bridge to the assets object. Aborts on naming conflict.  
- `setMeta(Asset, AssetMeta)`: adds a new `.meta` to the object (or overwrites an existing one).
- `getMeta(Asset) -> AssetMeta&`: gives access to the meta data of the given asset. Both mutable and const versions available.
- `loadMeta(File)`: loads `.meta` data in the given file/directory, recursively. Can also be used to reload `.meta`'s.
- `saveMeta(Asset)`: saves the current `.meta` data of the given asset.
- `upgrade(Asset&) -> bool`: upgrades an handle to a strong handle. Returns true on success.
- `update(Asset&) -> bool`: checks if the asset pointed to by the given handle as changed since the last update.
- `status(Asset) -> AssetStatus`: gets the current status of an asset (unknown, unloaded, loading, loaded).
- `set<T>(Asset, T)`: sets the asset data of the given asset.
- `get<T>(Asset, T)`: gives either read access or write access to an asset's data. Blocks until loaded, aborts on unknown.
- `create<T>(T) -> strong Asset`: creates a new asset with the given data and no corresponding `.meta`.
- `save(Asset)`: tries saving the changes made to the given asset. Aborts if it isn't writeable.

## Asset

`Asset` handles can be created in two ways:
- through the default constructor, which assigns them a random UUID. Useful for procedural assets.
- through a constructor which receives an asset name (e.g., `voxels/car.grd`).
Handles are always weak when they are created, which means there is no guarantee on the asset's data being available.

Handles can only become strong through the `Assets::upgrade` method, and their data and status can only be accessed through `Assets::get` and `Assets::status`.

## Bridge

Bridges have two virtual methods:
- `load(Assets&, Asset) -> bool`: should load the given asset, and call the `Assets::set` method to store it.
- `save(Assets&, Asset) -> bool`: should save the given asset to the file system.

Both methods should return `true` on success. By default, both have a blank implementation which always returns `false`.

# Use Cases

## Procedural assets

```cpp
struct MyData
{
  int x;
};

struct MyResource
{
  Asset myAsset;
};

void genAssets(Assets& assets, MyResource& rsc)
{
  rsc.myAsset = assets.create(MyData { .x = 1 });
}

void useGeneratedAsset(const Assets& assets, const MyResource& rsc)
{
  const auto& data = assets.get(rsc.myAsset);
  // do something with it
}
```

## TODO

...

**Comment by rsubtil** [comment]
I think the current proposal is good to go. It's hard to get a grasp on a good architecture for this, so I'd suggest starting with this, and wait to see how it evolves with the editor to better understand what's needed and what's not.
