### ISSUE TITLE
Log trace IDs to dispatcher systems

### ISSUE THREAD

**Issue by rsubtil** [GameDevTecnico/cubos#308]
The dispatcher is a complex system to interact with. Users are required to know it's inner details quite well, so errors have and will continue happening with it's usage. Therefore, it's important to improve the error/warning information so developers can know what they're doing wrong and how to fix it.

Tags are only used internally to group systems together. During the call chain compilation step, tag information has been mostly lost already. This makes it harder to display useful information as there's no good way of "printing function names". Here are the following solutions I've found so far:

- Use the `__FUNCTION__` identifier, which prints the current running function. It's what's used by the logger (spdlog) to print function names. But as we're not running the systems directly, we cannot use this to extract an arbitrary function name.
- Rely on [debugging information](https://stackoverflow.com/questions/40706805/how-to-convert-a-function-pointer-to-function-name), but it's ugly and Linux-only.
- Use macro and `#` operator to extract system name (`#define MY_FUNC(system) cubos.system(system, #system)`). But, macros...

**Comment by RiscadoA** [comment]
Another option is adding one more special pre processing step, like we're doing with the components.
I would like to avoid it, but it is something to consider if we don't find another way.

One way we could it with macros could be adding a `NamedSystem` class which acts as a functor (overrides the `()` operator) with a getter for the system name. We could add overrides for the `.system` methods for that type.stem
Then we can just add an utility macro `#define FUNCTION(system) NamedSystem(system, #system)` and use it like `cubos.system(FUNCTON(mySystem));`

**Comment by RiscadoA** [comment]
It was decided in the meeting that trace IDs would be added to systems, so that the user can specify them as if they were tags (e.g.: `cubos.system(x).trace("mySystem");`

**Comment by RiscadoA** [comment]
With the new system syntax introduced in #896 we simply specify the name of all systems through the .system method, so what remains to be done is to actually use this information.

**Comment by RiscadoA** [comment]
Closed in favor of already existing #414.
