### ISSUE TITLE
Allow resources to be added through `Commands`

### ISSUE THREAD

**Issue by RiscadoA** [GameDevTecnico/cubos#325]
Currently, the only way to add resources is using the `Cubos.addResource` method. This means that resources must be initialized in the plugin phase, or at least, left in a null state until the corresponding startup system runs.

This is error prone since it forces resources to be left in a unusable state temporarily, that leads do segfaults instead of providing useful error messages.

Instead, it would be much better to allow resources to be added at a later phase, using the commands.
For example, instead of:

```cpp
void windowPlugin(cubos)
{
  cubos.addResource(Window()); // invalid window handle, null until startup system
  cubos.startupSystem(system);
}

void system(Write<Window> window)
{
  window = new Window(); // now we can use it
}
```

We would use:

```cpp
void windowPlugin(cubos)
{
  cubos.startupSystem(system);
}

void system(Commands cmds)
{
  cmds.addResource(new Window()); // when a system tries to access it we can print a good looking error msg like 'unknown resource'.
}
```

**Comment by DiogoMendonc-a** [comment]
When this is done the GizmosRenderer resource should be changed to use this.
