### ISSUE TITLE
Use #pragma once instead of include guards

### ISSUE THREAD

**Issue by luishfonseca** [GameDevTecnico/cubos#331]
`#pragma once` might not be in the standard but is supported by every modern compiler, support won't be a problem.

Include guards are bulky, ugly and error prone. Having to open an existing header file, copy pasting and editing the guard every time is a chore and a typo might lead to cryptic errors.

We should discuss this.

**Comment by RiscadoA** [comment]
Let's start writing new code with `#pragma once`. Eventually we should open a PR to change the old files to it too
