### ISSUE TITLE
Import commonly used types from core into the engine namespace

### ISSUE THREAD

**Issue by RiscadoA** [GameDevTecnico/cubos#360]
Right now, when writing a plugin in the `cubos::engine` namespace, we have to write `core::ecs::Entity`, `core::ecs::Query`, `core::ecs::EventReader`, etc.
In my opinion since we want to 'hide' the core as much as possible from the user, we could add an alias to those types on the `cubos/engine/cubos.hpp` header.
E.g.:
```cpp
// prelude.hpp
namespace cubos::engine
{
  using Query = core::ecs::Query;
}

// my_plugin.hpp
namespace cubos::engine
{
  void myPlugin(Query<...>); // instead of core::ecs::Query
}
```

**Comment by roby2014** [comment]
So, everything that uses namespace stuff, we would have to create an alias for it? 
![imagem](https://github.com/GameDevTecnico/cubos/assets/47612455/d645c767-d5e6-4d10-accb-c5a8e4261dcc)
![imagem](https://github.com/GameDevTecnico/cubos/assets/47612455/e59f735d-32e8-4b0b-916c-d74f68789f4d)
i also saw some plugins already doing it
![imagem](https://github.com/GameDevTecnico/cubos/assets/47612455/fe49ac24-d380-4444-b5dc-cc6b82fdaa79)
