### ISSUE TITLE
Track key combos instead of keys with modifiers

### ISSUE THREAD

**Issue by luishfonseca** [GameDevTecnico/cubos#417]
If you want to release `C-a` when `Control` is released, then does it make sense to think in modifiers anymore? I don't think so. You are basically just considering that an action is only triggered when a group of keys is pressed.

You could make it so that instead of modifiers, you just store lists of keys to pressed: `Control+A` `A+B+C` - it could be useful to not be limited to modifiers.

_Originally posted by @RiscadoA in https://github.com/GameDevTecnico/cubos/pull/409#discussion_r1211251760_

**Comment by RiscadoA** [comment]
Maybe this would qualify as a good first issue
