### ISSUE TITLE
Add contribution guidelines to README.md

### ISSUE THREAD

**Issue by RiscadoA** [GameDevTecnico/cubos#47]
The README.md file is missing the contribution guidelines:

- pull requests should have a clear description of what they add
- code must be formatted using clang format
- camelCase is used for functions, methods, local variables and fields (no underscore prefixing on private fields)
- PascalCase is used for class names
- UPPER_CASE is used for macros
- snake_case is used for namespaces, folders and files
- each file should have an `#ifndef`include guard
- when closing a namespace the namespace name should be added as a comment, the same goes for if macros (`#ifdef`, ...)
- namespaces should match the directory structure, except `namespace impl`, which can be used to hide implementation details (check `cubos::gl::impl`)
- everything should be well documented (`///` style, check already existing files)

There should also be a mention to the gh page with documentation.

**Comment by joaopat98** [comment]
Add diagram of the game's systems (implemented and to be implemented), a high level explanation of how the system's interact.
