### ISSUE TITLE
Fix Renderer crash on changing windows

### ISSUE THREAD

**Issue by DiogoMendonc-a** [GameDevTecnico/cubos#479]
# Description

Zero-sized viewport results in dividing by zero which crashes the renderer.

# Reproduce

Minimizing any sample running the renderer crashes

# Screenshots

![relevant logs](https://github.com/GameDevTecnico/cubos/assets/44413591/a93c9606-843c-4310-baaf-82c5f0356580)

![relevant code](https://github.com/GameDevTecnico/cubos/assets/44413591/631679bf-1247-49e0-89b8-5ae60e933fa6)

**Comment by RiscadoA** [comment]
This problem will solve itself when we switch to the new render plugins.
