### ISSUE TITLE
Add Gizmos plugin

### ISSUE THREAD

**Issue by DiogoMendonc-a** [GameDevTecnico/cubos#511]
- [x] #512
- [x] #517
- [ ] #513
- [x] #514
- [x] #515
- [x] #516
- [x] #518
- [x] #842
- [ ] #717
- [x] #668
- [ ] #751

### Drawing Gizmos

```cpp
void sampleSystem(Write<Gizmos> gizmos) {
 glm::vec3 start = {0,0,0};
 glm::vec3 end = {10,0,0};
 gizmos.drawLine("sample line", start, end, Gizmos::Space::WorldSpace); 
}
```

### Drawing Wireframes

```cpp
void sampleSystem(Write<Gizmos> gizmos) {
 glm::vec3 start1 = {0,0,0};
 glm::vec3 end1 = {2,2,2};
 gizmos.drawBox("filled box", start1, end1); 

 glm::vec3 start2 = {3,0,0};
 glm::vec3 end2 = {5,2,2};
 gizmos.drawWireBox("wire only box", start2, end2);
}
```

### Changing Colour

```cpp
void sampleSystem(Write<Gizmos> gizmos) {
 gizmos.colour = {1,0,0,1};
 glm::vec3 start1 = {0,0,0};
 glm::vec3 end1 ={10,0,0};
 gizmos.drawLine("red line", start1, end1);

 gizmos.colour = {0,1,0,1};
 glm::vec3 start2 = {0,1,0};
 glm::vec3 end2 = {10,1,0};
 gizmos.drawLine("green line", start2, end2);
}
```

### Changing Lifetimes

```cpp
void sampleSystem(Write<Gizmos> gizmos) {
 glm::vec3 start1 = {0,0,0};
 glm::vec3 end1 = {10,0,0};
 // will stay on screen for exactly one frame, and DrawLine() will have to be called again the next frame to draw it.
 gizmos.drawLine("instant line", start1, end1);
 gizmos.drawLine("instant line", start1, end1, 0); // this is equivalent

 glm::vec3 start2 = {0,1,0};
 glm::vec3 end2 ={10,1,0};
 // will stay on screen for ten seconds, resetting each time DrawLine() is called
 gizmos.drawLine("green line", start2, end2, 10);
}
```

### Changing Space
It's likely someone will want to draw their gizmos on the world. For example drawing a raycast to check a bullet's direction.
It's also likely that someone will want to draw on screen. For example, a crosshair.
We'll need something to differentiate those calls, to avoid requiring the user from having to do the conversation maths.

#### World Space
The gizmo is drawn in world coordinates.

```cpp
void sampleSystem(Write<Gizmos> gizmos) {
 glm::vec3 start = {0,0,0};
 glm::vec3 end = {10,0,0};
 gizmos.drawLine("sample line", start, end, 0, Gizmos::Space::WorldSpace); 
}
```

#### Viewport Space
The gizmo is drawn in viewport coordinates. This means it will be drawn in relation to its position from the camera.

```cpp
void sampleSystem(Write<Gizmos> gizmos) {
 glm::vec3 start = {0,0,0};
 glm::vec3 end = {0.7,0.7,0};
 gizmos.drawLine("sample line", start, end, 0, Gizmos::Space::ViewportSpace); 
}
```

#### Screen Space
The gizmo is drawn in screen coordinates. The may difference from the Viewport Space is that the viewport space is attached to a camera, and thus is dependant on its output, the Screen Space is drawn on top of the entire application, so, for example, in a split screen game, the gizmo would cross screens.

```cpp
void sampleSystem(Write<Gizmos> gizmos) {
 glm::vec3 start = {0,0,0};
 glm::vec3 end = {0.7,0.7,0};
 gizmos.drawLine("sample line", start, end, 0, Gizmos::Space::ScreenSpace); 
}
```

### Gizmo interaction
We'll want to interact with gizmos, from clicking on them to dragging.

```cpp
glm::vec4 colour = {1,0,0,1};
void sampleSystem(Write<Gizmos> gizmos) {
 glm::vec3 start = {0,0,0};
 glm::vec3 end = {8,8,0};
 gizmos.colour = colour;
 gizmos.drawBox("colour changing box", start, end);
 if(gizmos.pressed("colour changing box")) {
  colour = {0,1,0,1};
 }
 else {
  colour = {1,0,0,1};
 }
}
```

In this case the box drawn is in a different colour depending on whether or not it is being held down.

### IDs
For the interaction purposes, we'll need a way of identifying which gizmo is which. That is the purpose of the IDs, the first argument of every draw function I've written here. I wrote in every call to better identify what the drawn gizmo should be, but it make no sense to me requiring every single gizmo to have an explicit identifier, so we can default them to `""`. It also makes sense to me to allow multiple gizmos sharing an id, and having the interaction behaviour trigger on any of them being pressed. For example:
```cpp
glm::vec4 colour = {1,0,0,1};
void sampleSystem(Write<Gizmos> gizmos) {
 glm::vec3 start = {0,0,0};
 glm::vec3 end = {2,2,2};
 gizmos.drawBox("pair of boxes", start, end);

 glm::vec3 start2 = {3,0,0};
 glm::vec3 end2 = {5,2,2};
 gizmos.drawBox("pair of boxes", start2, end2);

 if(gizmos.pressed("pair of boxes")) {
  // Some behaviour
 }
}
```

(If we don't make a specific check for it, this system will allow us to ask `if(gizmos.pressed(""))` to get if any gizmo without an ID has been pressed. Seems chaotic)

**Comment by RiscadoA** [comment]
Closing this as the gizmos plugin is pretty much done. The remaining sub issues will remain open
