### ISSUE TITLE
Settings

### ISSUE THREAD

**Issue by joaopat98** [GameDevTecnico/cubos#6]
- [ ] Parse Settings File
- [x] Retrieve Settings on request with required defaults
- [x] Update Settings values

**Comment by RicardoEPRodrigues** [comment]
Hello, I just wanted to share some thoughts.

What are these settings for exactly? Perhaps a concrete example might help reduce implementation efforts.

Is it for engine-specific properties? Or can it be a generic system for engine plus game? Should the settings be split?

Hope these questions help define the issue better.

**Comment by ratuspro** [comment]
I think we can close this issue without the parsing from file.
We should assume that something external to the Settings singleton will populate it.
Potentially calling `setString` will be enought right now
