### ISSUE TITLE
Spdlog can't be updated to versions after v1.9.1

### ISSUE THREAD

**Issue by luishfonseca** [GameDevTecnico/cubos#619]
# Description

CUBOS. will fail to compile recent spdlog versions

# Reproduce

1. Checkout the spdlog submodule at v1.10.0
2. Try to compile

# Expected behaviour
It should compile

# Additional context
Fixing this would also allow to use the system installed spdlog instead of building it.
There's also some weird interference with fmt that blocks it from being updated to recent versions.
These errors can be seen on this [action run](https://github.com/GameDevTecnico/cubos/actions/runs/6358186083/job/17270192137)

**Comment by roby2014** [comment]
Closing this because #823 .
