### ISSUE TITLE
Enforce conventional commits through a CI action

### ISSUE THREAD

**Issue by RiscadoA** [GameDevTecnico/cubos#626]
# Problem
Right now its possible to have commits on the main branch which violate conventional commits.

# Solution
We should have a CI action which checks if the commit message follows the expected pattern, and if the scope's are valid.

**Comment by roby2014** [comment]
Found this: https://github.com/webiny/action-conventional-commits
Is it okay to only run this action on pull requests? Or do you want it to run in main always as well?

**Comment by RiscadoA** [comment]
LGTM, we can keep it on PRs yes :relieved:
