### ISSUE TITLE
Voxel objects rendered red in samples in some GPUs

### ISSUE THREAD

**Issue by RiscadoA** [GameDevTecnico/cubos#653]
# Description

In some machines all voxel objects are being rendered as if only the red channel was available.
Surprisingly, it doesn't apply to the background of the renderer sample.

# Reproduce

Confirmed to happen at least in some of models of Intel UHD graphics.

# Expected behaviour
Should show all colors.

# Screenshots
![image](https://github.com/GameDevTecnico/cubos/assets/32821840/0ced3841-c945-4bb0-a917-3237f49360f0)

# Additional context
After investigating a capture made using RenderDoc I found that the light buffer had zero lights, except that the ambient light was set to `(1, 0, 0, 0)`. This means that the red color we're seeing is just the object under a red light.

**Comment by Dacops** [comment]
Issue appears to be fixed 
![Screenshot 2024-07-18 151707](https://github.com/user-attachments/assets/b75aa221-9f8f-4c87-ac75-70b180714564)
![Screenshot 2024-07-18 151744](https://github.com/user-attachments/assets/49624536-40e8-406f-b37f-eb2545c66409)

**Comment by Dacops** [comment]
Issue appears to be fixed 
![Screenshot 2024-07-18 151707](https://github.com/user-attachments/assets/c68467b6-a853-4eee-ad73-1e8ada4f6c93)
![Screenshot 2024-07-18 151744](https://github.com/user-attachments/assets/5b1343b8-be0b-422a-ab0c-9b6e556d1214)
