### ISSUE TITLE
Add With and Without filters to queries

### ISSUE THREAD

**Issue by luishfonseca** [GameDevTecnico/cubos#682]
# Problem
Right now the only way to filter out entities with certain components is by reading those components.
This means that even if our system is just checking if an entity has a component and not accessing its data, it can't run at the same time as a system which is writing to that component.

# Solution
Add `With<Component>`  and `Without<Component>` filters to the query, which don't provide data access.

**Comment by RiscadoA** [comment]
Wait these filters wouldn't solve the problem. They would be equivalent to Read/Write but without the data access. We need something else which allows checking if an entity has a component independently of the query ig?

**Comment by luishfonseca** [comment]
True, it's an harder problem to solve than i tough. Feel free to rename and edit my request

**Comment by RiscadoA** [comment]
Created another issue for the dynamic component checking part: #683.
