### ISSUE TITLE
Implement reflection for `std::string`

### ISSUE THREAD

**Issue by RiscadoA** [GameDevTecnico/cubos#687]
# Problem
Currently we can't reflect strings.

# Solution
We should provide a reflection declaration at `cubos/core/reflection/external/string.hpp`.

**Comment by roby2014** [comment]
Isn't this already implemented?
- https://github.com/GameDevTecnico/cubos/blob/main/core/include/cubos/core/reflection/external/string.hpp
- https://github.com/GameDevTecnico/cubos/blob/main/core/src/cubos/core/reflection/external/string.cpp
