### ISSUE TITLE
Window/Input Manager

### ISSUE THREAD

**Issue by joaopat98** [GameDevTecnico/cubos#7]
- [x] Create windows
- [x] Input Bindings
Hardware that is connected to specific actions (WASD, Spacebar, left joystick, etc.)
- [x] Input Actions
Specific actions that result from a player's input (move, jump, etc.)

**Comment by ratuspro** [comment]
Can this be closed @joaopat98 @DannyIsYog?

**Comment by RiscadoA** [comment]
No, we still have no input manager, just window events.

**Comment by DannyIsYog** [comment]
Lambda functions don't work when using them as callback on the register binding functions, let it be given by us or the programmer. Need to find a work around that.
