### ISSUE TITLE
Asset is nuked when save fails

### ISSUE THREAD

**Issue by RiscadoA** [GameDevTecnico/cubos#708]
# Description

When saving fails, the `FileBridge` has already opened the file for writing and thus it is erased.

# Expected behaviour

`FileBridge` should first write to a backup, and only if the write is successful should the original file be replaced.

**Comment by roby2014** [comment]
I might have an idea on how to do this, which is:
```cpp
bool FileBridge::save(const Assets& assets, const AnyAsset& handle) {
    auto path = assets.readMeta(handle)->get("path").value();
    auto backupPath = path + ".backup";

    auto file = FileSystem::create(backupPath); // create a backup file
    // if (file == nullptr) ... cubos_error, return false

    auto stream = file->open(File::OpenMode::Write);
    // if (stream == nullptr) ... cubos_error, return false

    if (!this->saveToFile(assets, handle, *stream)) {
        // cubos_error, return false
    }

    // close the stream?
    // destroy path file
    // rename backupPath to path

    return true;
}
```

Is this ok or do you have a better suggestion?

**Comment by RiscadoA** [comment]
This is what I imagined, LGTM :) I would maybe rename backup to swp, as it doesnt reallt backup anything, its just the new data
