### ISSUE TITLE
Include full sample code in documentation examples

### ISSUE THREAD

**Issue by roby2014** [GameDevTecnico/cubos#735]
Currently, our documentation includes examples without providing the complete sample code at the end of each instance. While it is a valid approach to keep some examples concise, the consistency in our documentation style is essential.

I believe there is value in providing the full example code at the end of the examples. This approach makes it easier for users who prefer to copy and paste the code directly, improving the overall user experience.

However, it's essential to acknowledge that some examples may be lengthy, and including the entire code block might not always be practical. Hence, I suggest that we discuss this matter in our next meeting to decide on a standardized approach that strikes the right balance between comprehensiveness and practicality.

**Comment by RiscadoA** [comment]
Discussed this in the meeting and we should add a link to the corresponding GitHub folder.
