### ISSUE TITLE
Typo in example page name `Introducion and Custom Bridges` 

### ISSUE THREAD

**Issue by RiscadoA** [GameDevTecnico/cubos#744]
# Expected behaviour
Should be `Introduction and Custom Bridges`.

# Screenshots
![image](https://github.com/GameDevTecnico/cubos/assets/32821840/f22d0835-dc70-442d-9bfe-0309b2e4a7e0)

**Comment by roby2014** [comment]
🇪🇸 🇪🇸 🇪🇸 🇪🇸
