### ISSUE TITLE
Replace serialization by reflection when using ECS 

### ISSUE THREAD

**Issue by RiscadoA** [GameDevTecnico/cubos#748]
# Checklist
- [x] #749
- [x] #773
- [x] #750
- [x] #769

# Description
Currently we can't remove the old serialization entirely from the ECS yet because there's still a lot of 'ECS user' code depending on it. We should adapt that code to instead use reflection to achieve the same goals.

**Comment by roby2014** [comment]
Done?!

**Comment by RiscadoA** [comment]
Yes :relieved:
