### ISSUE TITLE
Current tesseratos sample crashes because of `assetExplorer` plugin

### ISSUE THREAD

**Issue by roby2014** [GameDevTecnico/cubos#793]
# Description

Current tesseratos sample crashes when selecting `.cubos` scenes from Asset Explorer.

# Reproduce

Run tesseratos sample and select any `.cubos` element in the Asset Explorer.

# Screenshots
![imagem](https://github.com/GameDevTecnico/cubos/assets/47612455/f093871d-82c7-47fc-902e-99cf657bc715)

# Additional context
OS: Windows

**Comment by RiscadoA** [comment]
Whoops, introduced this in #733. I changed blueprint to start ensuring entity names follow a given format, so now _ is prohibited. Forgot to update the tesseratos sample :(
