### ISSUE TITLE
CMake version `3.22.1` not supported out of the box

### ISSUE THREAD

**Issue by roby2014** [GameDevTecnico/cubos#838]
# Description

`CMakeLists.txt` requires minimum cmake version `3.20` (https://github.com/GameDevTecnico/cubos/blob/main/CMakeLists.txt#L4). However, I've tried compiling with `3.22.1` and no success.

![imagem](https://github.com/GameDevTecnico/cubos/assets/47612455/990db3fe-8e37-445b-8dbd-dff2b075434e)

# Solution
Either find out what is triggering this error OR change minimum version required.

**Comment by RiscadoA** [comment]
We now use CMake 3.25
