### ISSUE TITLE
Unfriendly error on `JSONDeserializer` when an object is invalid

### ISSUE THREAD

**Issue by RiscadoA** [GameDevTecnico/cubos#841]
# Description
When a type provides a `FieldsTrait` but a primitive value is found on the JSON value, the JSON deserializer gives a non-useful error message.

# Expected behaviour
It should just say something like 'Expected an object, found ...'

**Comment by Dacops** [comment]
As this issue is trivial, fix will be joined with #1162

**Comment by Dacops** [comment]
Closed with #1162
